# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - askmalibu

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://github.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_315a347cb50f4559822ee0ff5f567b67 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d7d73b0d75694186b665f0344a610651 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: github.com/${{ secrets.AzureAppService_ContainerUsername_315a347cb50f4559822ee0ff5f567b67 }}/sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'askmalibu'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_64ce3acbdeb64d9c9f7293b07c70d1db }}
        images: 'github.com/${{ secrets.AzureAppService_ContainerUsername_315a347cb50f4559822ee0ff5f567b67 }}/sampleappaoaichatgpt.azurecr.io/sample-app-aoai-chatgpt:${{ github.sha }}'